# Generated by Django 5.2 on 2025-04-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('ROUND', 'Okrągły'), ('SQUARE', 'Kwadratowy'), ('RECT', 'Prostokątny'), ('D_Shape', 'Marcepan')], max_length=10)),
                ('size_label', models.CharField(choices=[('Fi22', 'Fi22'), ('Fi25', 'Fi25'), ('Fi30', 'Fi30'), ('Fi40', 'Fi40'), ('Fi50', 'Fi50'), ('40x40', '40x40'), ('25x25', '25x25'), ('30x30', '30x30'), ('30x10', '30x10'), ('40x10', '40x10'), ('40x20', '40x20'), ('50x25', '50x25'), ('100x20', '100x20'), ('Owal', 'Owal'), ('Marcepan', 'Marcepan')], max_length=20)),
            ],
            options={
                'unique_together': {('shape', 'size_label')},
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('AL', 'Aluminium'), ('A304', 'AISI 304'), ('A304_Poler', 'AISI 304 Poler'), ('A316', 'AISI 316'), ('A316_Poler', 'AISI 316 Poler'), ('MS', 'Mosiądz')], max_length=10)),
                ('shape', models.CharField(choices=[('ROUND', 'Okrągły'), ('SQUARE', 'Kwadratowy'), ('RECT', 'Prostokątny'), ('D_Shape', 'Marcepan')], max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.shapesize')),
            ],
        ),
    ]
