# Generated by Django 5.2 on 2025-04-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='material',
            field=models.CharField(choices=[('AL_SUR', 'Aluminium Surowe'), ('AL_C35', 'Aluminium Anoda Czarna C35'), ('AL_C31', 'Aluminium Anoda Srebrna C31'), ('AL_SG', 'Aluminium Anoda Srebrna Gładka'), ('AL_C30', 'Aluminium Anoda Inox C30'), ('AL_LAK_CZ', 'Aluminium Lakier Czarny'), ('A304', 'AISI 304'), ('A304_Poler', 'AISI 304 Poler'), ('A316', 'AISI 316'), ('A316_Poler', 'AISI 316 Poler'), ('MS', 'Mosiądz')], max_length=10),
        ),
    ]
