# Generated by Django 5.2 on 2025-04-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_containerentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerentry',
            old_name='weight_kg',
            new_name='total_weight_kg',
        ),
    ]
