# Generated by Django 5.2 on 2025-04-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_rename_weight_kg_containerentry_total_weight_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerentry',
            old_name='size',
            new_name='size_id',
        ),
    ]
