# Generated by Django 5.2 on 2025-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_rename_size_id_containerentry_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
