# Generated by Django 5.2 on 2025-05-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_tarebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapesize',
            name='size_label',
            field=models.CharField(choices=[('Fi22', 'Fi22'), ('Fi25', 'Fi25'), ('Fi30', 'Fi30'), ('Fi40', 'Fi40'), ('Fi50', 'Fi50'), ('40x40', '40x40'), ('25x25', '25x25'), ('30x30', '30x30'), ('30x10', '30x10'), ('40x10', '40x10'), ('40x20', '40x20'), ('50x25', '50x25'), ('100x20', '100x20'), ('Owal', 'Owal'), ('Marcepan', 'Marcepan'), ('Kieszen', 'Kieszeniówka'), ('45x45', '45x45'), ('Fi30x1.0', 'Fi30x1.0'), ('60x60', '60x60')], max_length=20),
        ),
    ]
