# Generated by Django 5.2 on 2025-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0008_alter_shapesize_size_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='shape',
            field=models.CharField(choices=[('ROUND', 'Okrągły'), ('SQUARE', 'Kwadratowy'), ('RECT', 'Prostokątny'), ('Other', 'Inny')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shapesize',
            name='shape',
            field=models.CharField(choices=[('ROUND', 'Okrągły'), ('SQUARE', 'Kwadratowy'), ('RECT', 'Prostokątny'), ('Other', 'Inny')], max_length=10),
        ),
    ]
