# Generated by Django 5.2 on 2025-05-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0009_alter_container_shape_alter_shapesize_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSizeDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('weight_per_meter', models.DecimalField(decimal_places=4, max_digits=10)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.shapesize')),
            ],
            options={
                'unique_together': {('material', 'size')},
            },
        ),
    ]
