# Generated by Django 5.2 on 2025-05-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0010_materialsizedensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='material',
            field=models.CharField(choices=[('AL_SUR', 'Aluminium Surowe'), ('AL_C35', 'Aluminium Anoda Czarna C35'), ('AL_C30', 'Aluminium Anoda Srebrna C30'), ('AL_SG', 'Aluminium Anoda Srebrna Gładka'), ('AL_C31', 'Aluminium Anoda Inox C31'), ('AL_LAK_CZ', 'Aluminium Lakier Czarny'), ('A304', 'AISI 304'), ('A304_Poler', 'AISI 304 Poler'), ('A316', 'AISI 316'), ('A316_Poler', 'AISI 316 Poler'), ('MS', 'Mosiądz')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shapesize',
            name='size_label',
            field=models.CharField(choices=[('Fi22', 'Fi22'), ('Fi25', 'Fi25'), ('Fi30', 'Fi30'), ('Fi40', 'Fi40'), ('Fi50', 'Fi50'), ('40x40', '40x40'), ('25x25', '25x25'), ('30x30', '30x30'), ('30x10', '30x10'), ('40x10', '40x10'), ('40x20', '40x20'), ('50x25', '50x25'), ('100x20', '100x20'), ('Owal', 'Owal'), ('Marcepan', 'Marcepan'), ('Kieszen', 'Kieszeniówka'), ('45x45', '45x45'), ('Fi30x1.0', 'Fi30x1.0'), ('60x60', '60x60'), ('Fi25x1.0', 'Fi25x1.0')], max_length=20),
        ),
    ]
